# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      
    - name: Install dependencies
      run: yarn install
    - name: Eslint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "dist"
        target: ${{ secrets.SERVER_PATH }}
    - name: Notification
      uses: erguotou520/instant-access-action@v1
      if: ${{ success() }}
      with:
        channel: "3fa27c0affa54c069e428af95f0f98fa"
        head: "{{branchName}}部署完成"
        body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
    - name: Notification
      uses: erguotou520/instant-access-action@v1
      if: ${{ failure() }}
      with:
        channel: "3fa27c0affa54c069e428af95f0f98fa"
        head: "{{branchName}}部署失败"
        body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
